//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schubert.Framework.Security.AntiXss.Globalization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalizationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalizationStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Schubert.Framework.Security.AntiXss.Globalization.GlobalizationStrings", typeof(GlobalizationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Count cannot be negative or greater than the length of the buffer. 的本地化字符串。
        /// </summary>
        internal static string CountOutOfRange {
            get {
                return ResourceManager.GetString("CountOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Count cannot be greater than the number of bytes in the buffer from the index to the end. 的本地化字符串。
        /// </summary>
        internal static string CountTooLarge {
            get {
                return ResourceManager.GetString("CountTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index cannot be negative or greater than the length of the buffer. 的本地化字符串。
        /// </summary>
        internal static string IndexOutOfRange {
            get {
                return ResourceManager.GetString("IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Character set name ({0}) is invalid or not installed. 的本地化字符串。
        /// </summary>
        internal static string InvalidCharset {
            get {
                return ResourceManager.GetString("InvalidCharset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text code page ({0}) is invalid or not installed. 的本地化字符串。
        /// </summary>
        internal static string InvalidCodePage {
            get {
                return ResourceManager.GetString("InvalidCodePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Culture name ({0}) is unknown. 的本地化字符串。
        /// </summary>
        internal static string InvalidCultureName {
            get {
                return ResourceManager.GetString("InvalidCultureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Locale ID ({0}) is not valid. 的本地化字符串。
        /// </summary>
        internal static string InvalidLocaleId {
            get {
                return ResourceManager.GetString("InvalidLocaleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 maxCharacters cannot be negative. 的本地化字符串。
        /// </summary>
        internal static string MaxCharactersCannotBeNegative {
            get {
                return ResourceManager.GetString("MaxCharactersCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text code page for character set ({0}) is not installed. 的本地化字符串。
        /// </summary>
        internal static string NotInstalledCharset {
            get {
                return ResourceManager.GetString("NotInstalledCharset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text code page ({0}) for character set ({1}) is not installed. 的本地化字符串。
        /// </summary>
        internal static string NotInstalledCharsetCodePage {
            get {
                return ResourceManager.GetString("NotInstalledCharsetCodePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text code page ({0}) is not installed. 的本地化字符串。
        /// </summary>
        internal static string NotInstalledCodePage {
            get {
                return ResourceManager.GetString("NotInstalledCodePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offset cannot be negative or greater than the length of the buffer. 的本地化字符串。
        /// </summary>
        internal static string OffsetOutOfRange {
            get {
                return ResourceManager.GetString("OffsetOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Priority list cannot include code pages that are not detectable. 的本地化字符串。
        /// </summary>
        internal static string PriorityListIncludesNonDetectableCodePage {
            get {
                return ResourceManager.GetString("PriorityListIncludesNonDetectableCodePage", resourceCulture);
            }
        }
    }
}
