//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schubert.Framework.Security.AntiXss.TextConverters {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextConvertersStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextConvertersStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Schubert.Framework.Security.AntiXss.TextConverters.TextConvertersStrings", typeof(TextConvertersStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 access should be either Read or Write. 的本地化字符串。
        /// </summary>
        internal static string AccessShouldBeReadOrWrite {
            get {
                return ResourceManager.GetString("AccessShouldBeReadOrWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attribute collection is not properly initialized, you must retrieve one with Attributes property of HtmlTagContext before using. 的本地化字符串。
        /// </summary>
        internal static string AttributeCollectionNotInitialized {
            get {
                return ResourceManager.GetString("AttributeCollectionNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attribute id is invalid. 的本地化字符串。
        /// </summary>
        internal static string AttributeIdInvalid {
            get {
                return ResourceManager.GetString("AttributeIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attribute id cannot be Unknown. 的本地化字符串。
        /// </summary>
        internal static string AttributeIdIsUnknown {
            get {
                return ResourceManager.GetString("AttributeIdIsUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attribute name cannot be empty 的本地化字符串。
        /// </summary>
        internal static string AttributeNameIsEmpty {
            get {
                return ResourceManager.GetString("AttributeNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HtmlTagContextAttribute is not properly initialized, you must retrieve one through HtmlTagContext.Attributes collection. 的本地化字符串。
        /// </summary>
        internal static string AttributeNotInitialized {
            get {
                return ResourceManager.GetString("AttributeNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You should write attribute name before writing attribute value 的本地化字符串。
        /// </summary>
        internal static string AttributeNotStarted {
            get {
                return ResourceManager.GetString("AttributeNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HtmlTagContextAttribute is not valid for the current context. Do not store context attribute across callbacks. 的本地化字符串。
        /// </summary>
        internal static string AttributeNotValidForThisContext {
            get {
                return ResourceManager.GetString("AttributeNotValidForThisContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HtmlTagContextAttribute is not valid in this state. 的本地化字符串。
        /// </summary>
        internal static string AttributeNotValidInThisState {
            get {
                return ResourceManager.GetString("AttributeNotValidInThisState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 value cannot be smaller than 1K or bigger than 80K bytes. 的本地化字符串。
        /// </summary>
        internal static string BufferSizeValueRange {
            get {
                return ResourceManager.GetString("BufferSizeValueRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Callback tag already has been deleted. 的本地化字符串。
        /// </summary>
        internal static string CallbackTagAlreadyDeleted {
            get {
                return ResourceManager.GetString("CallbackTagAlreadyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Callback tag already has been written to output. 的本地化字符串。
        /// </summary>
        internal static string CallbackTagAlreadyWritten {
            get {
                return ResourceManager.GetString("CallbackTagAlreadyWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The source stream does not support reading. 的本地化字符串。
        /// </summary>
        internal static string CannotReadFromSource {
            get {
                return ResourceManager.GetString("CannotReadFromSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot seek before the beginning of the stream. 的本地化字符串。
        /// </summary>
        internal static string CannotSeekBeforeBeginning {
            get {
                return ResourceManager.GetString("CannotSeekBeforeBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Length of the stream cannot be negative. 的本地化字符串。
        /// </summary>
        internal static string CannotSetNegativelength {
            get {
                return ResourceManager.GetString("CannotSetNegativelength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConverterReader or TextWriter cannot be used as output with this converter because the converter produces byte output. Use Stream. 的本地化字符串。
        /// </summary>
        internal static string CannotUseConverterReader {
            get {
                return ResourceManager.GetString("CannotUseConverterReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConverterWriter or TextReader cannot be used as input with this converter because the converter accepts byte input. Use Stream. 的本地化字符串。
        /// </summary>
        internal static string CannotUseConverterWriter {
            get {
                return ResourceManager.GetString("CannotUseConverterWriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot write other tags inside &lt;{0}&gt; element. 的本地化字符串。
        /// </summary>
        internal static string CannotWriteOtherTagsInsideElement {
            get {
                return ResourceManager.GetString("CannotWriteOtherTagsInsideElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The destination stream does not support writing. 的本地化字符串。
        /// </summary>
        internal static string CannotWriteToDestination {
            get {
                return ResourceManager.GetString("CannotWriteToDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot write HTML while input tag or attribute copy is pending. 的本地化字符串。
        /// </summary>
        internal static string CannotWriteWhileCopyPending {
            get {
                return ResourceManager.GetString("CannotWriteWhileCopyPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HtmlTagContext is not valid in this state. 的本地化字符串。
        /// </summary>
        internal static string ContextNotValidInThisState {
            get {
                return ResourceManager.GetString("ContextNotValidInThisState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot continue using ConverterReader after exception is thrown. 的本地化字符串。
        /// </summary>
        internal static string ConverterReaderInInconsistentStare {
            get {
                return ResourceManager.GetString("ConverterReaderInInconsistentStare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot continue using ConverterStream after exception is thrown. 的本地化字符串。
        /// </summary>
        internal static string ConverterStreamInInconsistentStare {
            get {
                return ResourceManager.GetString("ConverterStreamInInconsistentStare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot continue using ConverterWriter after exception is thrown. 的本地化字符串。
        /// </summary>
        internal static string ConverterWriterInInconsistentStare {
            get {
                return ResourceManager.GetString("ConverterWriterInInconsistentStare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Count cannot be negative or greater than the length of the buffer. 的本地化字符串。
        /// </summary>
        internal static string CountOutOfRange {
            get {
                return ResourceManager.GetString("CountOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Count cannot be greater than the number of bytes in buffer from index till the end. 的本地化字符串。
        /// </summary>
        internal static string CountTooLarge {
            get {
                return ResourceManager.GetString("CountTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An I/O error occurred while creating the file: {0}. 的本地化字符串。
        /// </summary>
        internal static string CreateFileFailed {
            get {
                return ResourceManager.GetString("CreateFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End tag cannot have any attributes 的本地化字符串。
        /// </summary>
        internal static string EndTagCannotHaveAttributes {
            get {
                return ResourceManager.GetString("EndTagCannotHaveAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Html tag nesting too deep, cannot convert this document. 的本地化字符串。
        /// </summary>
        internal static string HtmlNestingTooDeep {
            get {
                return ResourceManager.GetString("HtmlNestingTooDeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index cannot be negative or greater than the length of the buffer. 的本地化字符串。
        /// </summary>
        internal static string IndexOutOfRange {
            get {
                return ResourceManager.GetString("IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input document is too complex. 的本地化字符串。
        /// </summary>
        internal static string InputDocumentTooComplex {
            get {
                return ResourceManager.GetString("InputDocumentTooComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InputEncoding property is required for this conversion. 的本地化字符串。
        /// </summary>
        internal static string InputEncodingRequired {
            get {
                return ResourceManager.GetString("InputEncodingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text code page ({0}) is invalid or not installed. 的本地化字符串。
        /// </summary>
        internal static string InvalidCodePage {
            get {
                return ResourceManager.GetString("InvalidCodePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid configuration, expected boolean property ({0}). 的本地化字符串。
        /// </summary>
        internal static string InvalidConfigurationBoolean {
            get {
                return ResourceManager.GetString("InvalidConfigurationBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid configuration, expected integer property ({0}). 的本地化字符串。
        /// </summary>
        internal static string InvalidConfigurationInteger {
            get {
                return ResourceManager.GetString("InvalidConfigurationInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid configuration, expected stream property ({0}). 的本地化字符串。
        /// </summary>
        internal static string InvalidConfigurationStream {
            get {
                return ResourceManager.GetString("InvalidConfigurationStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The sum of offset and count ({0}) is larger than the array length ({1}). 的本地化字符串。
        /// </summary>
        internal static string LengthExceeded {
            get {
                return ResourceManager.GetString("LengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 maxCharacters cannot be negative. 的本地化字符串。
        /// </summary>
        internal static string MaxCharactersCannotBeNegative {
            get {
                return ResourceManager.GetString("MaxCharactersCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offset cannot be negative or greater than the length of the buffer. 的本地化字符串。
        /// </summary>
        internal static string OffsetOutOfRange {
            get {
                return ResourceManager.GetString("OffsetOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Converter object parameters cannot be changed after object is being used 的本地化字符串。
        /// </summary>
        internal static string ParametersCannotBeChangedAfterConverterObjectIsUsed {
            get {
                return ResourceManager.GetString("ParametersCannotBeChangedAfterConverterObjectIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Priority list cannot include code pages which are not detectable 的本地化字符串。
        /// </summary>
        internal static string PriorityListIncludesNonDetectableCodePage {
            get {
                return ResourceManager.GetString("PriorityListIncludesNonDetectableCodePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This property cannot be used in simple codepage conversion mode 的本地化字符串。
        /// </summary>
        internal static string PropertyNotValidForCodepageConversionMode {
            get {
                return ResourceManager.GetString("PropertyNotValidForCodepageConversionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This property cannot be used in text extraction mode 的本地化字符串。
        /// </summary>
        internal static string PropertyNotValidForTextExtractionMode {
            get {
                return ResourceManager.GetString("PropertyNotValidForTextExtractionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This stream does not support reading. 的本地化字符串。
        /// </summary>
        internal static string ReadUnsupported {
            get {
                return ResourceManager.GetString("ReadUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This stream does not support seeking. 的本地化字符串。
        /// </summary>
        internal static string SeekUnsupported {
            get {
                return ResourceManager.GetString("SeekUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag id is invalid. 的本地化字符串。
        /// </summary>
        internal static string TagIdInvalid {
            get {
                return ResourceManager.GetString("TagIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag id cannot be Unknown. 的本地化字符串。
        /// </summary>
        internal static string TagIdIsUnknown {
            get {
                return ResourceManager.GetString("TagIdIsUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag name cannot be empty. 的本地化字符串。
        /// </summary>
        internal static string TagNameIsEmpty {
            get {
                return ResourceManager.GetString("TagNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You should write a tag with WriteTag before writing tag attributes 的本地化字符串。
        /// </summary>
        internal static string TagNotStarted {
            get {
                return ResourceManager.GetString("TagNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag is too long, buffer reallocation has failed. 的本地化字符串。
        /// </summary>
        internal static string TagTooLong {
            get {
                return ResourceManager.GetString("TagTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConverterWriter or TextReader cannot be used as input with this converter. This converter accepts byte input (use Stream). 的本地化字符串。
        /// </summary>
        internal static string TextReaderUnsupported {
            get {
                return ResourceManager.GetString("TextReaderUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConverterReader or TextWriter cannot be used as output with this converter. This converter produces byte output (use Stream). 的本地化字符串。
        /// </summary>
        internal static string TextWriterUnsupported {
            get {
                return ResourceManager.GetString("TextWriterUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Too many iterations to flush the converter. 的本地化字符串。
        /// </summary>
        internal static string TooManyIterationsToFlushConverter {
            get {
                return ResourceManager.GetString("TooManyIterationsToFlushConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Too many iterations to process input chunk. 的本地化字符串。
        /// </summary>
        internal static string TooManyIterationsToProcessInput {
            get {
                return ResourceManager.GetString("TooManyIterationsToProcessInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Too many iterations to produce any output. 的本地化字符串。
        /// </summary>
        internal static string TooManyIterationsToProduceOutput {
            get {
                return ResourceManager.GetString("TooManyIterationsToProduceOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write should not be called for ConverterStream after Flush. 的本地化字符串。
        /// </summary>
        internal static string WriteAfterFlush {
            get {
                return ResourceManager.GetString("WriteAfterFlush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This stream does not support writing. 的本地化字符串。
        /// </summary>
        internal static string WriteUnsupported {
            get {
                return ResourceManager.GetString("WriteUnsupported", resourceCulture);
            }
        }
    }
}
